### ISSUE TITLE
[Community poll / discussion] Generating HTML via Yii helpers

### ISSUE THREAD

**Issue by arogachev** [yiisoft/html#116]
Do you use or going to use Yii to generate HTML? This means using stuff like:

```php
Html::a('Text', 'https://example.com');
```

Instead of

```html
<a href="https://example.com">Text</a>
```

As we all know JS frameworks evolved dramatically since Yii 2 times, and now situation is different. Frameworks like Yii are often used only to build REST APIs. Using classic approach still has it own benefits and can be used for MVP, low budget projects and so on. This does not mean that this feature and widgets based on it will be abandoned, but rather the focus can be shifted on more important backend related packages.

:+1: - Use / going to use
:-1:  - Do not use / not going to use
:call_me_hand:  - It depends on a project (you can write details in a comment)

Feel free to share you thoughts and ideas.

**Comment by bit-io** [comment]
Как подмечено фреймовики используются в основном для создания REST API, а для внешнего интерфейса можно юзать стороние шаблонизаторы, сделать акцент на более важные концептуальные вещи.

**Comment by tomaszkane** [comment]
@arogachev as You say, I use Yii-HTML to fast create some backend/admin-panel (server side render). Every main feature is implemented as REST API for React/Gatsby based frontend.
So yii-html and yii-bootstrap5 will be used etc.

**Comment by WeeSee** [comment]
We should provide gii templates which only use Yii helpers to generate Html.
Once I started this, for me code looks cleaner and easy to write. The PHP/Html mix is a mess
