### ISSUE TITLE
Html::renderAttribute() when attribute name is null or empty string

### ISSUE THREAD

**Issue by es-sayers** [yiisoft/html#215]
### What steps will reproduce the problem?
Html::renderTagAttributes(['' => 'empty string']);
Html::renderTagAttributes([null => 'null value']);

### What is the expected result?
Exception?

### What do you get instead?
' ="empty string"'
' ="null value"'

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.5
| PHP version      | 
| Operating system |

**Comment by vjik** [comment]
Done by #212
