### ISSUE TITLE
Html::renderTagAttributes() Unable to have attributes that equal ""

### ISSUE THREAD

**Issue by es-sayers** [yiisoft/html#216]
### What steps will reproduce the problem?

`Html::renderTagAttributes(['test' => ""]);`

### What is the expected result?

`' test=""'`

### What do you get instead?

`' test'`

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.5
| PHP version      | 
| Operating system |

**Comment by samdark** [comment]
Why do you need empty attributes?

**Comment by vjik** [comment]
It's OK. See https://github.com/yiisoft/html/issues/79
