### ISSUE TITLE
The implicit logic of Html::escapeJsRegularExpression

### ISSUE THREAD

**Issue by vjik** [yiisoft/html#23]
Now function work with correct regexps:

```php
Html::escapeJsRegularExpression('/([a-z0-9-]+)/Ugimex'); // /([a-z0-9-]+)/gim
Html::escapeJsRegularExpression('/mag/imgx'); // /mag/img
```

... and with regexps without delimiters, but with brackets:

```php
Html::escapeJsRegularExpression('([a-z0-9-]+)'); // /[a-z0-9-]+/
```

... and NOT WORK with regexps without delimiters and withour brackets:

```php
Html::escapeJsRegularExpression('(a)bc'); // /a)b/
Html::escapeJsRegularExpression('.*'); // empty string
```

-----

I see two variants:

**Variant one**

Allow use method only with correct regexps with delimiters:

```php
Html::escapeJsRegularExpression('/([a-z0-9-]+)/Ugimex'); // /([a-z0-9-]+)/gim
Html::escapeJsRegularExpression('/mag/imgx'); // /mag/img
Html::escapeJsRegularExpression('([a-z0-9-]+)'); // InvalidArgumentException
Html::escapeJsRegularExpression('(a)bc'); // InvalidArgumentException
Html::escapeJsRegularExpression('.*'); // InvalidArgumentException
```

**Variant two**

All regexps without delimiters wrap to `/`:

```php
Html::escapeJsRegularExpression('/([a-z0-9-]+)/Ugimex'); // /([a-z0-9-]+)/gim
Html::escapeJsRegularExpression('/mag/imgx'); // /mag/img
Html::escapeJsRegularExpression('([a-z0-9-]+)'); // /([a-z0-9-]+)/
Html::escapeJsRegularExpression('(a)bc'); // /(a)bc/
Html::escapeJsRegularExpression('.*'); // /.*/
```

**Comment by samdark** [comment]
1. There's another variant — to optionally specify delimiter.
2. If choosing between variants, I'm for variant 1.
3. There's no use-case for the method, we can just delete it. For validation we're going to use https://caniuse.com/input-pattern instead of JS regex.

**Comment by vjik** [comment]
We need this method also for `pattern` attribute. From [docs](https://html.spec.whatwg.org/multipage/input.html#the-pattern-attribute):

> If specified, the attribute's value must match the JavaScript Pattern[+U, +N] production.

I think we need save this method, but remake it:

```php
Html::prepareInputPattern(string $regexp, bool $extract = true, $delimiter = null);
```

Examples:

```php
Html::prepareInputPattern('/([a-z0-9-]+)/Ugimex'); // ([a-z0-9-]+)
Html::prepareInputPattern('/([a-z0-9-]+)/Ugimex', false); // /([a-z0-9-]+)/Ugimex
Html::prepareInputPattern('/([a-z0-9-]+)/Ugimex', true, '/'); // ([a-z0-9-]+)
Html::prepareInputPattern('/([a-z0-9-]+)/Ugimex', true, '~'); // InvalidArgumentException - incorrect regexp
Html::prepareInputPattern('/([a-z0-9-]+)/Ugimex', true, '//'); // InvalidArgumentException - incorrect delimiter
Html::prepareInputPattern('/mag/imgx'); // mag
Html::prepareInputPattern('([a-z0-9-]+)'); // InvalidArgumentException - incorrect regexp
Html::prepareInputPattern('(a)bc'); // InvalidArgumentException - incorrect regexp
Html::prepareInputPattern('.*'); // InvalidArgumentException - incorrect regexp
```

**Comment by samdark** [comment]
Escaping rules are different in JavaScript blocks and HTML attributes.

**Comment by samdark** [comment]
https://wonko.com/post/html-escaping

**Comment by vjik** [comment]
For escapig HTML has method `Html::encode`.

`prepareInputPattern`probably bad name. Maybe better `preparePcreRegexpToPattern`...

Task of `Html::preparePcreRegexpToPattern` convert PCRE regular expression to expression for `pattern` attribute.

Example of use:

```php
Html::textInput('number', '', [
	'pattern' => Html::preparePcreRegexpToPattern('/\d/'),
]);
```

**Comment by samdark** [comment]
There are two things to consider:

1. Preparing pattern itself.
2. Escaping it for being a value of HTML attribute (quotes, double quotes etc.)
