### ISSUE TITLE
Consider encoding everything by default

### ISSUE THREAD

**Issue by samdark** [yiisoft/html#42]
See https://github.com/yiisoft/yii2/issues/18404. In Yii 3 we can change it safely.

**Comment by dicrtarasov** [comment]
Good idea!
But also we need an option to disable encoding in some situations where content is HTML, for example labels with markup.

**Comment by samdark** [comment]
Yes. That is true.

**Comment by samdark** [comment]
| Method              | Encode by default | Can change |
|---------------------|-------------------|------------|
| tag                 | ❌                 | ❌          |
| beginTag            | ❌                 | ❌          |
| endTag              | ❌                 | ❌          |
| style               | ❌                 | ❌          |
| script              | ❌                 | ❌          |
| cssFile             | ✔️                 | ❌          |
| jsFile              | ✔️                 | ❌          |
| a                   | ❌                 | ❌          |
| mailto              | ❌                 | ❌          |
| img                 | ✔️                 | ❌          |
| label               | ❌                 | ❌          |
| button              | ❌                 | ❌          |
| submitButton        | ❌                 | ❌          |
| resetButton         | ❌                 | ❌          |
| input               | ✔️                 | ❌          |
| buttonInput         | ✔️                 | ❌          |
| submitInput         | ✔️                 | ❌          |
| resetInput          | ✔️                 | ❌          |
| textInput           | ✔️                 | ❌          |
| hiddenInput         | ✔️                 | ❌          |
| passwordInput       | ✔️                 | ❌          |
| fileInput           | ✔️                 | ❌          |
| textarea            | ✔️                 | ❌          |
| radio               | ✔️                 | ❌          |
| checkbox            | ✔️                 | ❌          |
| dropDownList        | ✔️                 | ✔️          |
| listBox             | ✔️                 | ✔️          |
| checkboxList        | ✔️                 | ✔️          |
| radioList           | ✔️                 | ✔️          |
| div                 | ❌                 | ❌          |
| span                | ❌                 | ❌          |
| p                   | ❌                 | ❌          |
| ul                  | ✔️                 | ✔️          |
| ol                  | ✔️                 | ✔️          |
| renderSelectOptions | ✔️                 | ✔️          |
| renderTagAttributes | ✔️                 | ❌          |

**Comment by samdark** [comment]
General pattern:

1. For simple tags don't encode content. No way to enable it, use `Html::encode()`.
2. Always encode attributes. No way to disable it.
3. Encode list items by default, allow disabling it.

**Comment by samdark** [comment]
It is quite logical as it is and results in not that verbose syntax in templates. If we'll change it we'll have to turn encoding off for majority of simple tags all the time:

```php
Html::p('This was a <strong>strong</strong> feeling.', ['encode' => false]);
```

**Comment by dicrtarasov** [comment]
"no way to disable/enable it" sounds not good. Why not adding boolean "encode" option, which change default behavior? 
```php
Html::p('Some text', [
  'encode' => false
]);
```

Then use:
```php
$encode = ArrayHelper::remove($options, 'encode', true);
```

**Comment by Mister-42** [comment]
If you give a good use case to not encode attributes, I am sure it will be changed.

**Comment by dicrtarasov** [comment]
Sure, you can imagine good case, to not make things imposdible to disable.

**Comment by Mister-42** [comment]
Nope, never came across one.

**Comment by samdark** [comment]
@dicrtarasov of course, we want it to be configurable i.e. you will be able to disable encoding.

**Comment by samdark** [comment]
@Mister-42 the use-case to disable encoding is when you need some HTML. For example,

```php
Html::p('Hello, <strong>world!</strong>', [
  'encode' => false
]);
```

**Comment by Mister-42** [comment]
> @Mister-42 the use-case to disable encoding is when you need some HTML. For example,
> 
> ```
> Html::p('Hello, <strong>' . Html::encode($username). '</strong>!', [
>   'encode' => false
> ]);
> ```

No dispute there, but as you were specific about 'always encode **attributes**' that is what I replied on.

**Comment by samdark** [comment]
Ah, right. For attribute values I have no idea why disabling encoding might make sense. @dicrtarasov do you have any?

**Comment by dicrtarasov** [comment]
> Ah, right. For attribute values I have no idea why disabling encoding might make sense. @dicrtarasov do you have any?

I completely agree
