### ISSUE TITLE
When you set `''` in `class()` method it should not return `class=""` 

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/html#77]
| Q                | A
| ---------------- | ---
| Version          | 3
| PHP version      | 8.0 
| Operating system | Windows11

**Comment by vjik** [comment]
For remove attribute in other methods we use `null`, for example `->id(null)`. I think in `class` we also should use `null` for don't add class and empty string should add attribute. See PR https://github.com/yiisoft/html/pull/78, which allow pass `null` argument to methods `Tag::class()` and `Tag::replaceClass()`.

**Comment by samdark** [comment]
Empty `class` doesn't make sense so I agree with @terabytesoftw proposal.

**Comment by vjik** [comment]
this is incorrect. empty string and without attribute - this is different cases

**Comment by samdark** [comment]
Yes if we do not consider CSS semantics. If we do then empty "class" value doesn't make any sense.
