### ISSUE TITLE
For attributes with empty string generate `<tag attr>` instead of `<tag attr="">`

### ISSUE THREAD

**Issue by vjik** [yiisoft/html#79]
Quote from [HTML specification](https://html.spec.whatwg.org/): "The value, along with the "=" character, can be omitted altogether if the value is the empty string."

**Comment by WinterSilence** [comment]
@vjik only in HTML 5, XHML still use, `CAN` != `MUST`

**Comment by WinterSilence** [comment]
@samdark ок, XHTML5 still use (:
