### ISSUE TITLE
Implement itemsAttributes() for each items in checkboxlist and radiolist widget.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/html#82]
Proposal: 

```php
CheckboxList::create('test')
  ->items([1 => 'One', 2 => '<b>Two</b>',])
  ->itemsAttributes([1 => ['disabled' => true]])
  ->render(),
```

Currently attributes are applied to all items.

**Comment by samdark** [comment]
How about:

```php
CheckboxList::create('test')
  ->items([1 => (new Item('One')->disabled(), 2 => '<b>Two</b>',])
  ->render(),
```

**Comment by terabytesoftw** [comment]
> How about the following?
> 
> ```
> CheckboxList::create('test')
>   ->items([1 => (new Item('One')->disabled(), 2 => '<b>Two</b>',])
>   ->render(),
> ```

in widgets you use arrays, to define the items.

**Comment by samdark** [comment]
Yes. We're going to release 2.0.0 so can change that.

**Comment by vjik** [comment]
I suggest name `specificCheckboxAttributes` instead of `itemAttributes`, because we set attributes it is special for checkboxes.
